<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto

namespace App\Models\GPBMetadata;

class Analytics
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x02\x0A\x0Fanalytics.proto\x12\x08be.cloud\"\$\x0A\x0DPlayerRequest\x12\x13\x0A\x0Bplayer_name\x18\x01 \x01(\x09\"[\x0A\x0CPlayerStatus\x12\x13\x0A\x0Bplayer_name\x18\x01 \x01(\x09\x12\x12\x0A\x0Aheart_rate\x18\x02 \x01(\x05\x12\x0F\x0A\x07lactate\x18\x03 \x01(\x02\x12\x11\x0A\x09exhausted\x18\x04 \x01(\x082V\x0A\x10AnalyticsService\x12B\x0A\x0FGetPlayerStatus\x12\x17.be.cloud.PlayerRequest\x1A\x16.be.cloud.PlayerStatusB(P\x01\xCA\x02\x0AApp\\Models\xE2\x02\x16App\\Models\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

