// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

@com.google.protobuf.Generated
public final class Analytics extends com.google.protobuf.GeneratedFile {
  private Analytics() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "Analytics");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_PlayerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_be_cloud_PlayerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_PlayerStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_be_cloud_PlayerStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017analytics.proto\022\010be.cloud\"#\n\rPlayerReq" +
      "uest\022\022\n\nplayerName\030\001 \001(\t\"Y\n\014PlayerStatus" +
      "\022\022\n\nplayerName\030\001 \001(\t\022\021\n\theartRate\030\002 \001(\005\022" +
      "\017\n\007lactate\030\003 \001(\002\022\021\n\texhausted\030\004 \001(\0102V\n\020A" +
      "nalyticsService\022B\n\017GetPlayerStatus\022\027.be." +
      "cloud.PlayerRequest\032\026.be.cloud.PlayerSta" +
      "tusB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_be_cloud_PlayerRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_be_cloud_PlayerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_be_cloud_PlayerRequest_descriptor,
        new java.lang.String[] { "PlayerName", });
    internal_static_be_cloud_PlayerStatus_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_be_cloud_PlayerStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_be_cloud_PlayerStatus_descriptor,
        new java.lang.String[] { "PlayerName", "HeartRate", "Lactate", "Exhausted", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
