// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

@com.google.protobuf.Generated
public interface PlayerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.PlayerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();
}
