// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

@com.google.protobuf.Generated
public interface PlayerStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.PlayerStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  java.lang.String getPlayerName();
  /**
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  com.google.protobuf.ByteString
      getPlayerNameBytes();

  /**
   * <code>int32 heartRate = 2;</code>
   * @return The heartRate.
   */
  int getHeartRate();

  /**
   * <code>float lactate = 3;</code>
   * @return The lactate.
   */
  float getLactate();

  /**
   * <code>bool exhausted = 4;</code>
   * @return The exhausted.
   */
  boolean getExhausted();
}
