<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto

namespace App\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>be.cloud.PlayerRequest</code>
 */
class PlayerRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string player_name = 1;</code>
     */
    protected $player_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $player_name
     * }
     */
    public function __construct($data = NULL) {
        \App\Models\GPBMetadata\Analytics::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string player_name = 1;</code>
     * @return string
     */
    public function getPlayerName()
    {
        return $this->player_name;
    }

    /**
     * Generated from protobuf field <code>string player_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->player_name = $var;

        return $this;
    }

}

