<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto

namespace App\Models;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>be.cloud.PlayerStatus</code>
 */
class PlayerStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string player_name = 1;</code>
     */
    protected $player_name = '';
    /**
     * Generated from protobuf field <code>int32 heart_rate = 2;</code>
     */
    protected $heart_rate = 0;
    /**
     * Generated from protobuf field <code>float lactate = 3;</code>
     */
    protected $lactate = 0.0;
    /**
     * Generated from protobuf field <code>bool exhausted = 4;</code>
     */
    protected $exhausted = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $player_name
     *     @type int $heart_rate
     *     @type float $lactate
     *     @type bool $exhausted
     * }
     */
    public function __construct($data = NULL) {
        \App\Models\GPBMetadata\Analytics::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string player_name = 1;</code>
     * @return string
     */
    public function getPlayerName()
    {
        return $this->player_name;
    }

    /**
     * Generated from protobuf field <code>string player_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlayerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->player_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 heart_rate = 2;</code>
     * @return int
     */
    public function getHeartRate()
    {
        return $this->heart_rate;
    }

    /**
     * Generated from protobuf field <code>int32 heart_rate = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setHeartRate($var)
    {
        GPBUtil::checkInt32($var);
        $this->heart_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float lactate = 3;</code>
     * @return float
     */
    public function getLactate()
    {
        return $this->lactate;
    }

    /**
     * Generated from protobuf field <code>float lactate = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLactate($var)
    {
        GPBUtil::checkFloat($var);
        $this->lactate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool exhausted = 4;</code>
     * @return bool
     */
    public function getExhausted()
    {
        return $this->exhausted;
    }

    /**
     * Generated from protobuf field <code>bool exhausted = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setExhausted($var)
    {
        GPBUtil::checkBool($var);
        $this->exhausted = $var;

        return $this;
    }

}

