// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: analytics.proto
// Protobuf Java Version: 4.33.1

package be.cloud;

/**
 * Protobuf type {@code be.cloud.PlayerStatus}
 */
@com.google.protobuf.Generated
public final class PlayerStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:be.cloud.PlayerStatus)
    PlayerStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "PlayerStatus");
  }
  // Use PlayerStatus.newBuilder() to construct.
  private PlayerStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlayerStatus() {
    playerName_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return be.cloud.Analytics.internal_static_be_cloud_PlayerStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return be.cloud.Analytics.internal_static_be_cloud_PlayerStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            be.cloud.PlayerStatus.class, be.cloud.PlayerStatus.Builder.class);
  }

  public static final int PLAYERNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object playerName_ = "";
  /**
   * <code>string playerName = 1;</code>
   * @return The playerName.
   */
  @java.lang.Override
  public java.lang.String getPlayerName() {
    java.lang.Object ref = playerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      playerName_ = s;
      return s;
    }
  }
  /**
   * <code>string playerName = 1;</code>
   * @return The bytes for playerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlayerNameBytes() {
    java.lang.Object ref = playerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      playerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEARTRATE_FIELD_NUMBER = 2;
  private int heartRate_ = 0;
  /**
   * <code>int32 heartRate = 2;</code>
   * @return The heartRate.
   */
  @java.lang.Override
  public int getHeartRate() {
    return heartRate_;
  }

  public static final int LACTATE_FIELD_NUMBER = 3;
  private float lactate_ = 0F;
  /**
   * <code>float lactate = 3;</code>
   * @return The lactate.
   */
  @java.lang.Override
  public float getLactate() {
    return lactate_;
  }

  public static final int EXHAUSTED_FIELD_NUMBER = 4;
  private boolean exhausted_ = false;
  /**
   * <code>bool exhausted = 4;</code>
   * @return The exhausted.
   */
  @java.lang.Override
  public boolean getExhausted() {
    return exhausted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, playerName_);
    }
    if (heartRate_ != 0) {
      output.writeInt32(2, heartRate_);
    }
    if (java.lang.Float.floatToRawIntBits(lactate_) != 0) {
      output.writeFloat(3, lactate_);
    }
    if (exhausted_ != false) {
      output.writeBool(4, exhausted_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerName_);
    }
    if (heartRate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, heartRate_);
    }
    if (java.lang.Float.floatToRawIntBits(lactate_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, lactate_);
    }
    if (exhausted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, exhausted_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof be.cloud.PlayerStatus)) {
      return super.equals(obj);
    }
    be.cloud.PlayerStatus other = (be.cloud.PlayerStatus) obj;

    if (!getPlayerName()
        .equals(other.getPlayerName())) return false;
    if (getHeartRate()
        != other.getHeartRate()) return false;
    if (java.lang.Float.floatToIntBits(getLactate())
        != java.lang.Float.floatToIntBits(
            other.getLactate())) return false;
    if (getExhausted()
        != other.getExhausted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PLAYERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPlayerName().hashCode();
    hash = (37 * hash) + HEARTRATE_FIELD_NUMBER;
    hash = (53 * hash) + getHeartRate();
    hash = (37 * hash) + LACTATE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getLactate());
    hash = (37 * hash) + EXHAUSTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getExhausted());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static be.cloud.PlayerStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.PlayerStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.PlayerStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.PlayerStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.PlayerStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.PlayerStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.PlayerStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.PlayerStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static be.cloud.PlayerStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static be.cloud.PlayerStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.cloud.PlayerStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.PlayerStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(be.cloud.PlayerStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code be.cloud.PlayerStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:be.cloud.PlayerStatus)
      be.cloud.PlayerStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return be.cloud.Analytics.internal_static_be_cloud_PlayerStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return be.cloud.Analytics.internal_static_be_cloud_PlayerStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              be.cloud.PlayerStatus.class, be.cloud.PlayerStatus.Builder.class);
    }

    // Construct using be.cloud.PlayerStatus.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      playerName_ = "";
      heartRate_ = 0;
      lactate_ = 0F;
      exhausted_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return be.cloud.Analytics.internal_static_be_cloud_PlayerStatus_descriptor;
    }

    @java.lang.Override
    public be.cloud.PlayerStatus getDefaultInstanceForType() {
      return be.cloud.PlayerStatus.getDefaultInstance();
    }

    @java.lang.Override
    public be.cloud.PlayerStatus build() {
      be.cloud.PlayerStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public be.cloud.PlayerStatus buildPartial() {
      be.cloud.PlayerStatus result = new be.cloud.PlayerStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(be.cloud.PlayerStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.playerName_ = playerName_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.heartRate_ = heartRate_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lactate_ = lactate_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.exhausted_ = exhausted_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof be.cloud.PlayerStatus) {
        return mergeFrom((be.cloud.PlayerStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(be.cloud.PlayerStatus other) {
      if (other == be.cloud.PlayerStatus.getDefaultInstance()) return this;
      if (!other.getPlayerName().isEmpty()) {
        playerName_ = other.playerName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getHeartRate() != 0) {
        setHeartRate(other.getHeartRate());
      }
      if (java.lang.Float.floatToRawIntBits(other.getLactate()) != 0) {
        setLactate(other.getLactate());
      }
      if (other.getExhausted() != false) {
        setExhausted(other.getExhausted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              playerName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              heartRate_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 29: {
              lactate_ = input.readFloat();
              bitField0_ |= 0x00000004;
              break;
            } // case 29
            case 32: {
              exhausted_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object playerName_ = "";
    /**
     * <code>string playerName = 1;</code>
     * @return The playerName.
     */
    public java.lang.String getPlayerName() {
      java.lang.Object ref = playerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string playerName = 1;</code>
     * @return The bytes for playerName.
     */
    public com.google.protobuf.ByteString
        getPlayerNameBytes() {
      java.lang.Object ref = playerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string playerName = 1;</code>
     * @param value The playerName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      playerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string playerName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerName() {
      playerName_ = getDefaultInstance().getPlayerName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string playerName = 1;</code>
     * @param value The bytes for playerName to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      playerName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int heartRate_ ;
    /**
     * <code>int32 heartRate = 2;</code>
     * @return The heartRate.
     */
    @java.lang.Override
    public int getHeartRate() {
      return heartRate_;
    }
    /**
     * <code>int32 heartRate = 2;</code>
     * @param value The heartRate to set.
     * @return This builder for chaining.
     */
    public Builder setHeartRate(int value) {

      heartRate_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int32 heartRate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeartRate() {
      bitField0_ = (bitField0_ & ~0x00000002);
      heartRate_ = 0;
      onChanged();
      return this;
    }

    private float lactate_ ;
    /**
     * <code>float lactate = 3;</code>
     * @return The lactate.
     */
    @java.lang.Override
    public float getLactate() {
      return lactate_;
    }
    /**
     * <code>float lactate = 3;</code>
     * @param value The lactate to set.
     * @return This builder for chaining.
     */
    public Builder setLactate(float value) {

      lactate_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>float lactate = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLactate() {
      bitField0_ = (bitField0_ & ~0x00000004);
      lactate_ = 0F;
      onChanged();
      return this;
    }

    private boolean exhausted_ ;
    /**
     * <code>bool exhausted = 4;</code>
     * @return The exhausted.
     */
    @java.lang.Override
    public boolean getExhausted() {
      return exhausted_;
    }
    /**
     * <code>bool exhausted = 4;</code>
     * @param value The exhausted to set.
     * @return This builder for chaining.
     */
    public Builder setExhausted(boolean value) {

      exhausted_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool exhausted = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearExhausted() {
      bitField0_ = (bitField0_ & ~0x00000008);
      exhausted_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:be.cloud.PlayerStatus)
  }

  // @@protoc_insertion_point(class_scope:be.cloud.PlayerStatus)
  private static final be.cloud.PlayerStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new be.cloud.PlayerStatus();
  }

  public static be.cloud.PlayerStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlayerStatus>
      PARSER = new com.google.protobuf.AbstractParser<PlayerStatus>() {
    @java.lang.Override
    public PlayerStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlayerStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlayerStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public be.cloud.PlayerStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

